development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ruby_course_development
  pool: 5
  username: ruby_course_admin
  password: ruby_course_password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ruby_course_test
  pool: 5
  username: ruby_course_admin
  password: ruby_course_password

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ruby_course_production
  pool: 5
  username: ruby_course_admin
  password: ruby_course_password
